version: "3.7"

services:
  #   db_dev:
  #     image: mysql:5.7
  #     restart: always
  #     ports:
  #       - "3308:3306"
  #     environment:
  #       - MYSQL_USER=admin
  #       - MYSQL_DATABASE=mydb
  #       - MYSQL_PASSWORD=1205
  #       - MYSQL_ROOT_PASSWORD=1205
  #     command:
  #       - --character-set-server=utf8mb4
  #       - --collation-server=utf8mb4_unicode_ci
  #     volumes:
  #       - ./db_data:/var/lib/mysql

  redis:
    image: redis:6.0.5
    command: redis-server --requirepass 1205 --port 6379
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
# [redis]
# docker-compose exec redis bash
# redis-cli
# auth 1205
# keys *
